<?php
// @codingStandardsIgnoreFile
$_helper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
$scriptAdditionalTag = '';
 if ($_helper->isDevMoveJsBottomEnabled()) {
     $scriptAdditionalTag = ' data-exclude-this-tag="text/x-magento-template" ';
 }
$cspNonceProvider = $_helper->getCspNonceProvider();
if ($cspNonceProvider) {
    $scriptAdditionalTag .= ' nonce="'. $cspNonceProvider->generateNonce() .'"';
}
?>
<?php if ($this->isEnabled()) : ?>
    <?php $dataLayerObject = $this->getDataLayerAsJson(); ?>
<script<?= /* @noEscape */ $scriptAdditionalTag ?>>
        window.getWpCookie = function(name) {
            match = document.cookie.match(new RegExp(name + '=([^;]+)'));
            if (match) return decodeURIComponent(match[1].replace(/\+/g, ' ')) ;
        };

        window.dataLayer = window.dataLayer || [];
        <?php if ($dataLayerObject != '[[]]') : ?>
        var dlObjects = <?= /* @noEscape */ $dataLayerObject ?>;
        for (var i in dlObjects) {
            window.dataLayer.push({ecommerce: null});
            window.dataLayer.push(dlObjects[i]);
        }
        <?php endif; ?>
        var wpCookies = [<?= /* @noEscape */ $this->getWpCookiesForJs() ?>];
        wpCookies.map(function(cookieName) {
            var cookieValue = window.getWpCookie(cookieName);
            if (cookieValue) {
                var dlObject = {};
                dlObject[cookieName.replace('wp_', '')] = cookieValue;
                window.dataLayer.push(dlObject);
            }
        });
    </script>
<?php endif; ?>
